### ISSUE TITLE
[PMT] Link Contact Us Nav Button

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/mapscout-homepage#23]
Link the contact us button on the [navbar](https://github.com/GTBitsOfGood/mapscout-homepage/blob/develop/src/components/Nav.svelte) to https://bitsofgood.org/contact/

**Comment by cduffy8** [comment]
https://github.com/GTBitsOfGood/mapscout-homepage/pull/31#issue-2106714081
